import { describe, expect, it } from "vitest";
import { getEventPhase, getScheduleBuckets, initialPlayerUiState, playWithMutedFallback, playerUiReducer } from "./playerControls";
import { ufcSchedule } from "../config/ufcSchedule";
import type { UfcEvent } from "../config/ufcSchedule";

// A fixed reference instant plus a synthetic schedule so the schedule-helper
// tests stay deterministic and do NOT rot when ufcSchedule.ts is regenerated by
// the weekly `update:schedule` cron.
const NOW = Date.parse("2026-06-20T22:00:00Z");
const HOUR = 60 * 60 * 1000;

function makeEvent(id: string, startIso: string | null, opts: Partial<UfcEvent> = {}): UfcEvent {
  return {
    id,
    title: `Test ${id}`,
    shortTitle: id,
    dateLabel: "Test day",
    venue: "Test venue",
    city: "Test city",
    stream: "Paramount+",
    sourceUrl: `https://www.ufc.com/event/${id}`,
    mainCardIso: startIso,
    slots: startIso ? [{ label: "Main card", iso: startIso }] : [],
    ...opts,
  };
}

const liveEvent = makeEvent("live", new Date(NOW - HOUR).toISOString());
const nextEvent = makeEvent("next", new Date(NOW + 2 * HOUR).toISOString());
const laterEvent = makeEvent("later", new Date(NOW + 72 * HOUR).toISOString());
const replayEvent = makeEvent("replay", new Date(NOW - 10 * HOUR).toISOString());
const tbaEvent = makeEvent("tba", null, { dateIso: new Date(NOW + 200 * HOUR).toISOString() });
const syntheticSchedule: UfcEvent[] = [replayEvent, liveEvent, nextEvent, laterEvent, tbaEvent];

describe("player controls", () => {
  it("clamps volume and unmutes when volume is restored", () => {
    const muted = playerUiReducer(initialPlayerUiState, { type: "set-volume", volume: 0 });
    expect(muted.volume).toBe(0);
    expect(muted.muted).toBe(true);

    const audible = playerUiReducer(muted, { type: "set-volume", volume: 2 });
    expect(audible.volume).toBe(1);
    expect(audible.muted).toBe(false);
  });

  it("toggles stats and the more menu independently", () => {
    const stats = playerUiReducer(initialPlayerUiState, { type: "toggle-stats" });
    const menu = playerUiReducer(stats, { type: "toggle-more" });
    const closed = playerUiReducer(menu, { type: "set-more", open: false });

    expect(menu.statsOpen).toBe(true);
    expect(menu.moreMenuOpen).toBe(true);
    expect(closed.statsOpen).toBe(true);
    expect(closed.moreMenuOpen).toBe(false);
  });
});

describe("UFC schedule helpers", () => {
  it("detects a live event window", () => {
    expect(getEventPhase(liveEvent, NOW)).toBe("Now");
    expect(getEventPhase(nextEvent, NOW)).toBe("Next");
    expect(getEventPhase(replayEvent, NOW)).toBe("Replay");
    expect(getEventPhase(tbaEvent, NOW)).toBe("TBA");
  });

  it("returns current and upcoming events", () => {
    const buckets = getScheduleBuckets(syntheticSchedule, NOW);

    expect(buckets.current?.id).toBe("live");
    expect(buckets.next?.id).toBe("next");
    expect(buckets.upcoming.map((e) => e.id)).toEqual(["next", "later", "tba"]);
  });

  it("keeps generated schedule ids unique and TBA events date-sortable", () => {
    const ids = new Set(ufcSchedule.map((event) => event.id));
    const tbaEvents = ufcSchedule.filter((event) => event.slots.length === 0);

    expect(ids.size).toBe(ufcSchedule.length);
    expect(tbaEvents.length).toBeGreaterThan(0);
    expect(tbaEvents.every((event) => event.dateIso && getEventPhase(event, Date.parse("2026-06-20T22:00:00Z")) === "TBA")).toBe(
      true
    );
  });
});

describe("playWithMutedFallback", () => {
  function fakeVideo(opts: { rejectUnmuted?: boolean; rejectAlways?: boolean } = {}): HTMLVideoElement {
    return {
      muted: false,
      play(this: { muted: boolean }) {
        if (opts.rejectAlways) return Promise.reject(new DOMException("blocked", "NotAllowedError"));
        if (opts.rejectUnmuted && !this.muted) {
          return Promise.reject(new DOMException("blocked", "NotAllowedError"));
        }
        return Promise.resolve();
      }
    } as unknown as HTMLVideoElement;
  }

  it("keeps audio when the browser allows it", async () => {
    const video = fakeVideo();
    expect(await playWithMutedFallback(video)).toEqual({ playing: true, muted: false });
  });

  it("falls back to muted rather than showing nothing", async () => {
    // The mobile case: unmuted autoplay is refused, muted is allowed.
    const video = fakeVideo({ rejectUnmuted: true });
    expect(await playWithMutedFallback(video)).toEqual({ playing: true, muted: true });
    expect(video.muted).toBe(true);
  });

  it("reports failure when even muted playback is refused", async () => {
    const video = fakeVideo({ rejectAlways: true });
    expect(await playWithMutedFallback(video)).toEqual({ playing: false, muted: true });
  });

  it("does not retry when it was already muted", async () => {
    const video = fakeVideo({ rejectAlways: true });
    video.muted = true;
    expect(await playWithMutedFallback(video)).toEqual({ playing: false, muted: true });
  });
});
